name: Package Firewall
on:
  pull_request: { branches: [ main ] }
  push: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PHYLUM_ORG: ${{ secrets.PHYLUM_ORG }}        # e.g., myorg
      PHYLUM_GROUP: ${{ secrets.PHYLUM_GROUP }}    # e.g., demo_firewall (or leave empty)
      PHYLUM_API_KEY: ${{ secrets.PHYLUM_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Build PIP_INDEX_URL correctly (include %2F only if GROUP is set)
      - name: Compute PIP_INDEX_URL
        shell: bash
        run: |
          if [ -n "${PHYLUM_GROUP}" ]; then
            USER="${PHYLUM_ORG}%2F${PHYLUM_GROUP}"
          else
            USER="${PHYLUM_ORG}"
          fi
          echo "PIP_INDEX_URL=https://${USER}:${PHYLUM_API_KEY}@pypi.phylum.io/simple/" >> "$GITHUB_ENV"

      - name: Install deps (enforced by Phylum)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django checks
        run: |
          python manage.py check
          python manage.py migrate --noinput
