name: Package Firewall
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PHYLUM_ORG: ${{ secrets.PHYLUM_ORG }}
      PHYLUM_GROUP: ${{ secrets.PHYLUM_GROUP }}
      PHYLUM_API_KEY: ${{ secrets.PHYLUM_API_KEY }}
      # Point pip to Phylum; URL-encode the "/" in ORG/GROUP as %2F
      PIP_INDEX_URL: <https://$>{
        { secrets.PHYLUM_ORG }}%2F${{ secrets.PHYLUM_GROUP }}:${{ secrets.PHYLUM_API_KEY }}@pypi.phylum.io/simple/
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps (enforced by Phylum)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django checks
        run: |
          python manage.py check
          python manage.py migrate --noinput
